server:
  port: 6379
  shutdown_timeout: 5s
  max_connections: 1024

storage:
  partitions_number: 16
  gc_interval: 100ms
  gc_budget: 50ms

logger:
  level: info
  file_path: ./ararauna.log

wal:
  enabled: true
  dir: ./data/wal
  segment_size: 16777216 # 16MB
  sync_policy: always

metrics:
  enabled: true
  provider: victoriametrics
  push_url: "http://localhost:8428/api/v1/import/prometheus"
  job: ararauna
  push_interval: 10s
  extra_labels:
    instance: ararauna-1
